CREATE TABLE sellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL,
    region VARCHAR(80) NOT NULL,
    specialization VARCHAR(120) NOT NULL,
    daily_capacity INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sellers_email UNIQUE (email),
    CONSTRAINT chk_sellers_daily_capacity_positive CHECK (daily_capacity > 0)
);

CREATE INDEX idx_sellers_email ON sellers (email);
CREATE INDEX idx_sellers_region ON sellers (region);
CREATE INDEX idx_sellers_active ON sellers (active);
