CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(180),
    phone VARCHAR(30),
    source VARCHAR(80) NOT NULL,
    region VARCHAR(80) NOT NULL,
    status VARCHAR(30) NOT NULL,
    seller_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_leads_email UNIQUE (email),
    CONSTRAINT uk_leads_phone UNIQUE (phone),
    CONSTRAINT fk_leads_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
    CONSTRAINT chk_leads_contact_required CHECK (email IS NOT NULL OR phone IS NOT NULL),
    CONSTRAINT chk_leads_status CHECK (status IN ('NEW', 'ASSIGNED', 'CONTACTED', 'QUALIFIED', 'PROPOSAL', 'WON', 'LOST'))
);

CREATE INDEX idx_leads_email ON leads (email);
CREATE INDEX idx_leads_phone ON leads (phone);
CREATE INDEX idx_leads_status ON leads (status);
CREATE INDEX idx_leads_region ON leads (region);
CREATE INDEX idx_leads_source ON leads (source);
CREATE INDEX idx_leads_seller ON leads (seller_id);
CREATE INDEX idx_leads_created_at ON leads (created_at);
