CREATE TABLE lead_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL,
    action VARCHAR(40) NOT NULL,
    previous_value VARCHAR(1000),
    new_value VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lead_history_lead FOREIGN KEY (lead_id) REFERENCES leads(id),
    CONSTRAINT chk_lead_history_action CHECK (action IN (
        'LEAD_CREATED',
        'LEAD_UPDATED',
        'LEAD_STATUS_CHANGED',
        'LEAD_ASSIGNED',
        'LEAD_ACCEPTED',
        'LEAD_REJECTED'
    ))
);

CREATE INDEX idx_lead_history_lead ON lead_history (lead_id);
CREATE INDEX idx_lead_history_created_at ON lead_history (created_at);
CREATE INDEX idx_lead_history_action ON lead_history (action);
