CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    assigned_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP,
    rejected_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assignments_lead FOREIGN KEY (lead_id) REFERENCES leads(id),
    CONSTRAINT fk_assignments_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
    CONSTRAINT chk_assignments_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'TIMEOUT')),
    CONSTRAINT uk_assignments_active_lead UNIQUE (lead_id, status)
);

CREATE INDEX idx_assignments_lead ON assignments (lead_id);
CREATE INDEX idx_assignments_seller ON assignments (seller_id);
CREATE INDEX idx_assignments_status ON assignments (status);
CREATE INDEX idx_assignments_assigned_at ON assignments (assigned_at);
