CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    recipient VARCHAR(180) NOT NULL,
    type VARCHAR(30) NOT NULL,
    event VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    payload VARCHAR(1000) NOT NULL,
    error_message VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    CONSTRAINT fk_notifications_lead FOREIGN KEY (lead_id) REFERENCES leads(id),
    CONSTRAINT fk_notifications_seller FOREIGN KEY (seller_id) REFERENCES sellers(id),
    CONSTRAINT chk_notifications_type CHECK (type IN ('EMAIL', 'WEBHOOK')),
    CONSTRAINT chk_notifications_event CHECK (event IN ('LEAD_ASSIGNED', 'LEAD_ACCEPTED', 'LEAD_REJECTED', 'LEAD_REASSIGNED')),
    CONSTRAINT chk_notifications_status CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

CREATE INDEX idx_notifications_lead ON notifications (lead_id);
CREATE INDEX idx_notifications_seller ON notifications (seller_id);
CREATE INDEX idx_notifications_event ON notifications (event);
CREATE INDEX idx_notifications_status ON notifications (status);
CREATE INDEX idx_notifications_created_at ON notifications (created_at);
